#!/usr/bin/env php
<?php
declare(ticks=1);

use Paysera\Component\Console\Application;
use Paysera\Component\Console\PharKernel;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$require = true;
if (class_exists('Phar')) {
    try {
        Phar::mapPhar('raml-code-generator.phar');
        require_once 'phar://raml-code-generator.phar/vendor/autoload.php';
        $require = false;
    } catch (\PharException $e) {
    }
}
if ($require) {
    require_once __DIR__ . '/vendor/autoload.php';
}
unset($require);

$kernel = new PharKernel('phar', false);
$application = new Application($kernel);
$application->run(new ArgvInput(), new ConsoleOutput());

__HALT_COMPILER();
